function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 31-Oct-2019 11:46:53

% Create figure
figure1 = figure('PaperSize',[20.98404194812 29.67743169791],...
    'InvertHardcopy','off',...
    'Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,'LineWidth',2,'FontWeight','bold',...
    'FontSize',14);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 300]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 1]);
%% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',4);
set(plot1(1),'DisplayName','  Input','Color',[0 0 0]);
set(plot1(2),'Color',[0 0 1],'DisplayName','  Output');

% Create text
text('Parent',axes1,'String','mix','Position',[270 0.5 0],'FontSize',24);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'LineWidth',2);

